
WITHOUT mlflow.auto_log()

/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023/05/30 18:20:59 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under azureml://canadacentral.api.azureml.ms/mlflow/v2.0/subscriptions/733ee2ff-5a9c-42a2-8242-b8a500eb9f53/resourceGroups/rg-churn-pred-proj/providers/Microsoft.MachineLearningServices/workspaces/churn-pred-proj/experiments/40bb8617-fa5a-413e-bb6c-a097ded4fac8/runs/7f524732-fdeb-4f6a-8ecb-b8235f3ac836/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the tracking store. If logging to a mlflow server via REST, consider upgrading the server version to MLflow 1.7.0 or above. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2023/05/30 18:20:59 DEBUG mlflow.models.model: 
Traceback (most recent call last):
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/models/model.py", line 554, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 992, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1391, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 404, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 325, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'The request is invalid.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': 'e742499e32dac0eafde165ebe2b5ee3f', 'request': 'fac328b850b37b19'}, 'Environment': 'canadacentral', 'Location': 'canadacentral', 'Time': '2023-05-30T18:20:59.3158885+00:00', 'ComponentName': 'mlflow', 'error_code': 'INVALID_PARAMETER_VALUE'}


WITH mlFLow AUTOLOG()

2023/05/31 15:56:00 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed, possibly due older server version. The model artifacts have been logged successfully under azureml://canadacentral.api.azureml.ms/mlflow/v2.0/subscriptions/733ee2ff-5a9c-42a2-8242-b8a500eb9f53/resourceGroups/rg-churn-pred-proj/providers/Microsoft.MachineLearningServices/workspaces/churn-pred-proj/experiments/0bf049e2-19f0-485d-b4f8-29fe8709cb36/runs/4491180c-ed5e-4f5f-a0e0-93e6e9797282/artifacts. In addition to exporting model artifacts, MLflow clients 1.7.0 and above attempt to record model metadata to the tracking store. If logging to a mlflow server via REST, consider upgrading the server version to MLflow 1.7.0 or above. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2023/05/31 15:56:00 DEBUG mlflow.models.model: 
Traceback (most recent call last):
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/models/model.py", line 554, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 992, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1391, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 404, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 325, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/azureml-envs/azureml_5c112d3bae8c0c1df4f73c65ab585e79/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'The request is invalid.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': '8a30b454ee0260c1c7a3d0b461c13948', 'request': '687b7bff0003fd40'}, 'Environment': 'canadacentral', 'Location': 'canadacentral', 'Time': '2023-05-31T15:56:00.5974918+00:00', 'ComponentName': 'mlflow', 'error_code': 'INVALID_PARAMETER_VALUE'}